apiVersion: "1"          # ← Indica que quieres el schema v1 (o 2023-09-01)

services:
  # 1. Servicio web
  - type: web
    name: ocr-asistencias-web
    env: docker
    dockerfilePath: ./Dockerfile.web

    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: ocr-redis
          property: internalUrl
      - key: DATABASE_PATH
        value: /data/registros.db
      - key: UPLOAD_FOLDER
        value: /data/uploads
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/credentials.json

    secretFiles:
      - key: GOOGLE_CREDENTIALS_JSON
        path: /etc/secrets/credentials.json

    disk:                 # ← singular: un solo disco
      name: ocr-storage
      mountPath: /data
      sizeGB: 1

  # 2. Worker de segundo plano
  - type: worker
    name: ocr-asistencias-worker
    env: docker
    dockerfilePath: ./Dockerfile.worker

    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: ocr-redis
          property: internalUrl
      - key: DATABASE_PATH
        value: /data/registros.db
      - key: UPLOAD_FOLDER
        value: /data/uploads
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/credentials.json

    secretFiles:
      - key: GOOGLE_CREDENTIALS_JSON
        path: /etc/secrets/credentials.json

    disk:                 # usa el mismo volumen
      name: ocr-storage
      mountPath: /data

  # 3. Redis (cola de trabajos)
  - type: redis
    name: ocr-redis
    plan: free
