# render.yaml
# Versión corregida: El bloque 'disks' se mueve al nivel superior.

services:
  # 1. El servicio web que ejecuta la aplicación Flask
  - type: web
    name: ocr-asistencias-web
    env: docker
    dockerfilePath: ./Dockerfile.web
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: REDIS_URL
        fromService:
          type: redis
          name: ocr-redis
          property: internalUrl
      - key: DATABASE_PATH
        value: /data/registros.db
      - key: UPLOAD_FOLDER
        value: /data/uploads
      - fromSecretFile:
          name: google-credentials
          path: /etc/secrets/credentials.json
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/credentials.json
    disks:
      - name: ocr-storage # Nombre del disco a montar
        mountPath: /data   # Dónde se montará

  # 2. El trabajador en segundo plano que procesa los archivos
  - type: worker
    name: ocr-asistencias-worker
    env: docker
    dockerfilePath: ./Dockerfile.worker
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: REDIS_URL
        fromService:
          type: redis
          name: ocr-redis
          property: internalUrl
      - key: DATABASE_PATH
        value: /data/registros.db
      - fromSecretFile:
          name: google-credentials
          path: /etc/secrets/credentials.json
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/credentials.json
    disks:
      - name: ocr-storage # Nombre del disco a montar
        mountPath: /data   # Dónde se montará

  # 3. La base de datos Redis para la cola de trabajos
  - type: redis
    name: ocr-redis
    plan: free # O el plan que prefieras

# Definición del disco persistente a nivel de Blueprint
disks:
  - name: ocr-storage
    sizeGB: 1
