# render.yaml
# Versión final corregida. Se elimina la sección "disks:" del final
# y se simplifican las definiciones de los servicios.

services:
  # 1. El servicio web que ejecuta la aplicación Flask
  - type: web
    name: ocr-asistencias-web
    env: docker
    dockerfilePath: ./Dockerfile.web
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: REDIS_URL
        fromService:
          type: redis
          name: ocr-redis
          property: internalUrl
      - key: DATABASE_PATH
        value: /data/registros.db
      - key: UPLOAD_FOLDER
        value: /data/uploads
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/credentials.json # Ruta donde se montará el secreto
    secretFiles:
      - key: GOOGLE_CREDENTIALS_JSON # El nombre del secreto que crearás en Render
        path: /etc/secrets/credentials.json
    disks:
      - name: ocr-storage
        mountPath: /data
        sizeGB: 1

  # 2. El trabajador en segundo plano que procesa los archivos
  - type: worker
    name: ocr-asistencias-worker
    env: docker
    dockerfilePath: ./Dockerfile.worker
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.6
      - key: REDIS_URL
        fromService:
          type: redis
          name: ocr-redis
          property: internalUrl
      - key: DATABASE_PATH
        value: /data/registros.db
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: /etc/secrets/credentials.json
    secretFiles:
      - key: GOOGLE_CREDENTIALS_JSON
        path: /etc/secrets/credentials.json
    disks:
      - name: ocr-storage
        mountPath: /data
        # El tamaño (sizeGB) solo es necesario la primera vez que se define el disco.

  # 3. La base de datos Redis para la cola de trabajos
  - type: redis
    name: ocr-redis
    plan: free
